language: java
jdk:
  #- oraclejdk8
  #- oraclejdk9
  - openjdk8
before_install:

install:
  cd Spring-Cloud-Config-Client && mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
#  - "echo skipped" 
  - mvn test
# - mvn deploy
