language: java
jdk:
  #- oraclejdk8
  #- oraclejdk9
  - openjdk8
before_install:
  - "echo skipped"
install:
  cd Spring-Cloud-Config-Client && mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - "echo skipped"
script:
#  - "echo skipped" 
  - mvn install -Dmaven.javadoc.skip=true
# - mvn deploy
